name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        build:
          - platform: manylinux2014_x86_64
            installer: gztar
          - platform: macosx_10_15_x86_64
            installer: zip
          - platform: win_amd64
            installer: zip
          - platform: win_amd64
            installer: nsis

    steps:
    - name: Check out the branch
      uses: actions/checkout@v4
  
    - name: Install NSIS
      if: matrix.build.installer == 'nsis'
      run: |
        sudo apt-get -y update
        sudo apt-get -y install nsis
        makensis -VERSION
  
    - name: Set Up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt
  
    - name: Install Dependencies
      run: make install-dev
  
    - name: Build
      run: make build platform=${{ matrix.build.platform }} installer=${{ matrix.build.installer }}
  
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.build.platform }}-${{ matrix.build.installer }}
        path: src/dist
  merge:
   runs-on: ubuntu-latest
   timeout-minutes: 5
   needs: build

   steps:
   - name: Merge Artifacts
     uses: actions/upload-artifact/merge@v4
     with:
       name: build
       pattern: build-*
          