name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: dist
      - name: Print file structure
        run: ls -R dist
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/*
