name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/build.yml
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: dist
      - name: Print file structure
        run: ls -R dist
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
