name: Upgrade Dependencies

on: workflow_dispatch

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out the branch
        uses: actions/checkout@v3

      - name: Set Up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
          
      - name: Upgrade Dependencies
        run: |
          make upgrade

      - name: Publish Resolved Dependencies
        uses: actions/upload-artifact@v3
        with:
          name: requirements-lock
          path: requirements-lock.txt

      - name: Print Changes
        run: |
          git diff -U0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: upgrade-dependencies
          branch-suffix: timestamp
          commit-message: upgrade-dependencies
          title: Automated Dependency Upgrade
          body: |
            Automated dependency upgrade. Close and reopen to begin workflow runs.
